# Generated by Django 4.2.18 on 2025-04-30 19:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("address", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Client",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("full_name", models.CharField(blank=True, max_length=100)),
                ("business_name", models.CharField(blank=True, max_length=100)),
                ("display_name", models.CharField(max_length=100)),
                ("email", models.EmailField(blank=True, max_length=100)),
                ("phone", models.CharField(blank=True, max_length=16)),
                (
                    "shipping_address",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="address.address",
                    ),
                ),
            ],
        ),
    ]
