# Generated by Django 4.2.18 on 2025-04-30 19:11

from django.db import migrations, models
import tenant_users.permissions.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("organisation", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="User",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("password", models.CharField(max_length=128, verbose_name="password")),
                (
                    "last_login",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="last login"
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        db_index=True,
                        max_length=254,
                        unique=True,
                        verbose_name="Email Address",
                    ),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="active")),
                (
                    "is_verified",
                    models.BooleanField(default=False, verbose_name="verified"),
                ),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("owner", "Owner user role"),
                            ("admin", "Admin user role"),
                            ("manager", "Manager user role"),
                            ("employee", "Employee user role"),
                        ],
                        default="employee",
                        max_length=10,
                        verbose_name="User access role",
                    ),
                ),
                (
                    "first_name",
                    models.CharField(max_length=100, verbose_name="First Name"),
                ),
                (
                    "last_name",
                    models.CharField(max_length=100, verbose_name="Last Name"),
                ),
                ("designation", models.CharField(default="associate", max_length=100)),
                (
                    "tenants",
                    models.ManyToManyField(
                        blank=True,
                        help_text="The tenants this user belongs to.",
                        related_name="user_set",
                        to="organisation.tenant",
                        verbose_name="tenants",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
            bases=(
                models.Model,
                tenant_users.permissions.models.PermissionsMixinFacade,
            ),
        ),
    ]
