# Generated by Django 4.2.18 on 2025-04-30 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Item",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("goods", "Goods - Physical item"),
                            ("service", "Service - Service offered"),
                        ],
                        default="goods",
                        max_length=10,
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True)),
                ("sku", models.CharField(blank=True, max_length=128, unique=True)),
                ("upc", models.CharField(blank=True, max_length=64)),
                ("unit", models.CharField(blank=True, max_length=10)),
                ("sellable", models.BooleanField(default=False)),
                ("track_stock", models.BooleanField(default=False)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "cost_price",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=16, null=True
                    ),
                ),
                (
                    "selling_price",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=16, null=True
                    ),
                ),
                ("stock_on_hand", models.PositiveIntegerField(blank=True, null=True)),
                (
                    "low_stock_threshold",
                    models.PositiveIntegerField(blank=True, null=True),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True, db_index=True)),
            ],
            options={
                "ordering": ["-updated_at"],
            },
        ),
    ]
