# Generated by Django 4.2.18 on 2025-04-30 19:11

from django.db import migrations, models
import django_tenants.postgresql_backend.base


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Domain",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "domain",
                    models.CharField(db_index=True, max_length=253, unique=True),
                ),
                ("is_primary", models.BooleanField(db_index=True, default=True)),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="OrgAddress",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "line1",
                    models.CharField(
                        max_length=255, verbose_name="First line of address"
                    ),
                ),
                (
                    "line2",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        verbose_name="Second line of address",
                    ),
                ),
                ("city", models.CharField(max_length=255, verbose_name="City")),
                (
                    "state",
                    models.CharField(max_length=255, verbose_name="State/County"),
                ),
                (
                    "postcode",
                    models.CharField(max_length=64, verbose_name="Post/Zip-code"),
                ),
                ("country", models.CharField(max_length=64, verbose_name="Country")),
            ],
            options={
                "default_permissions": [],
            },
        ),
        migrations.CreateModel(
            name="Organisation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("branch", models.CharField(default="HQ", max_length=100)),
                ("description", models.TextField(blank=True, max_length=255)),
                ("phone", models.CharField(blank=True, max_length=15)),
                ("task_id", models.CharField(blank=True, max_length=50)),
            ],
            options={
                "permissions": [
                    ("custom_update_users", "Can add/remove users"),
                    ("custom_view_all_organisations", "Can view all organisations"),
                ],
            },
        ),
        migrations.CreateModel(
            name="Tenant",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "schema_name",
                    models.CharField(
                        db_index=True,
                        max_length=63,
                        unique=True,
                        validators=[
                            django_tenants.postgresql_backend.base._check_schema_name
                        ],
                    ),
                ),
                ("slug", models.SlugField(blank=True, verbose_name="Tenant URL Name")),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("modified", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=100)),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
