# Generated by Django 4.2.18 on 2025-04-30 19:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("organisation", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="tenant",
            name="owner",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AddField(
            model_name="organisation",
            name="address",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="organisations",
                to="organisation.orgaddress",
            ),
        ),
        migrations.AddField(
            model_name="organisation",
            name="tenant",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="organisation",
                to="organisation.tenant",
            ),
        ),
        migrations.AddField(
            model_name="domain",
            name="tenant",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="domains",
                to="organisation.tenant",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="organisation",
            unique_together={("name", "branch")},
        ),
    ]
