from typing import Any

import jwt
from django.conf import settings
from django.http import HttpRequest

from acct.people.auth.manager import get_jwt_manager

ACCT_AUTH_HEADER = "HTTP_AUTHORIZATION_BEARER"
DEFAULT_AUTH_HEADER = "HTTP_AUTHORIZATION"
AUTH_HEADER_PREFIXES = ["JWT", "BEARER"]
JWT_ACCESS_TYPE = "access"
JWT_THIRDPARTY_ACCESS_TYPE = "thirdparty"
JWT_ACCT_OWNER_NAME = "acct"
JWT_OWNER_FIELD = "owner"


def get_token_from_request(request: HttpRequest) -> str | None:
    auth_token: str | None = request.META.get(ACCT_AUTH_HEADER)

    if not auth_token:
        auth = request.META.get(DEFAULT_AUTH_HEADER, "").split(maxsplit=1)

        if len(auth) == 2 and auth[0].upper() in AUTH_HEADER_PREFIXES:
            auth_token = auth[1]
    return auth_token


def is_acct_token(token: str) -> bool:
    """Confirm that token was generated by Acct."""
    try:
        payload = jwt.decode(token, options={"verify_signature": False})
    except jwt.PyJWTError:
        return False
    owner = payload.get(JWT_OWNER_FIELD)
    if not owner or owner != JWT_ACCT_OWNER_NAME:
        return False
    return True


def jwt_decode(
    token: str, verify_expiration=settings.JWT_EXPIRE, verify_aud: bool = False
) -> dict[str, Any]:
    jwt_manager = get_jwt_manager()
    return jwt_manager.decode(token, verify_expiration, verify_aud=verify_aud)
