# Generated by Django 4.2.18 on 2025-04-30 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Address",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "line1",
                    models.CharField(
                        max_length=255, verbose_name="First line of address"
                    ),
                ),
                (
                    "line2",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        verbose_name="Second line of address",
                    ),
                ),
                ("city", models.CharField(max_length=255, verbose_name="City")),
                (
                    "state",
                    models.CharField(max_length=255, verbose_name="State/County"),
                ),
                (
                    "postcode",
                    models.CharField(max_length=64, verbose_name="Post/Zip-code"),
                ),
                ("country", models.CharField(max_length=64, verbose_name="Country")),
                ("phone_number", models.CharField(blank=True, max_length=16)),
            ],
            options={
                "verbose_name": "Address",
                "verbose_name_plural": "Addresses",
                "abstract": False,
            },
        ),
    ]
